//
//Copyright © 2021 Ci4Rail GmbH <engineering@ci4rail.com>
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: binaryIoTypeA.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigurationControlSet to pass to Functionblock.ConfigurationControl.functionSpecificConfigurationControlSet hook
type ConfigurationControlSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Map to enable fritting on binary output channels. This activates a cyclically higher current at the channel outputs to prevent corrison over time
	// LSB is Output0, 1: fritting enabled, 0: fritting disabled
	OutputFrittingMap uint32 `protobuf:"fixed32,1,opt,name=outputFrittingMap,proto3" json:"outputFrittingMap,omitempty"`
	// Map to enable the output watchdog for binary output channels. The output watchdog is activated if the output is not updated for a certain time.
	// LSB is Output0, 1: output watchdog enabled, 0: disabled
	OutputWatchdogMap uint32 `protobuf:"fixed32,2,opt,name=outputWatchdogMap,proto3" json:"outputWatchdogMap,omitempty"`
	// The output watchdog timeout in seconds.
	OutputWatchdogTimeout uint32 `protobuf:"fixed32,3,opt,name=outputWatchdogTimeout,proto3" json:"outputWatchdogTimeout,omitempty"`
}

func (x *ConfigurationControlSet) Reset() {
	*x = ConfigurationControlSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationControlSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationControlSet) ProtoMessage() {}

func (x *ConfigurationControlSet) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationControlSet.ProtoReflect.Descriptor instead.
func (*ConfigurationControlSet) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigurationControlSet) GetOutputFrittingMap() uint32 {
	if x != nil {
		return x.OutputFrittingMap
	}
	return 0
}

func (x *ConfigurationControlSet) GetOutputWatchdogMap() uint32 {
	if x != nil {
		return x.OutputWatchdogMap
	}
	return 0
}

func (x *ConfigurationControlSet) GetOutputWatchdogTimeout() uint32 {
	if x != nil {
		return x.OutputWatchdogTimeout
	}
	return 0
}

// ConfigurationControlSetResponse to pass to Functionblock.ConfigurationControl.functionSpecificConfigurationControlSetResponse hook
type ConfigurationControlSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationControlSetResponse) Reset() {
	*x = ConfigurationControlSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationControlSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationControlSetResponse) ProtoMessage() {}

func (x *ConfigurationControlSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationControlSetResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationControlSetResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{1}
}

// ConfigurationControlGet to pass to Functionblock.ConfigurationControl.functionSpecificConfigurationControlGet hook
type ConfigurationControlGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationControlGet) Reset() {
	*x = ConfigurationControlGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationControlGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationControlGet) ProtoMessage() {}

func (x *ConfigurationControlGet) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationControlGet.ProtoReflect.Descriptor instead.
func (*ConfigurationControlGet) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{2}
}

// ConfigurationControlGetResponse to pass to Functionblock.ConfigurationGetResponse.functionSpecificConfigurationControlGetResponse hook
// Returns the current hardware configuration
type ConfigurationControlGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Map to enable fritting on output channels. This activates a cyclically higher current at the channel outputs to prevent corrison over time
	Fritting uint32 `protobuf:"fixed32,2,opt,name=fritting,proto3" json:"fritting,omitempty"`
}

func (x *ConfigurationControlGetResponse) Reset() {
	*x = ConfigurationControlGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationControlGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationControlGetResponse) ProtoMessage() {}

func (x *ConfigurationControlGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationControlGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationControlGetResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigurationControlGetResponse) GetFritting() uint32 {
	if x != nil {
		return x.Fritting
	}
	return 0
}

// ConfigurationControlDescribe to pass to Functionblock.ConfigurationControl.functionSpecificConfigurationControlDescribe hook
type ConfigurationControlDescribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurationControlDescribe) Reset() {
	*x = ConfigurationControlDescribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationControlDescribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationControlDescribe) ProtoMessage() {}

func (x *ConfigurationControlDescribe) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationControlDescribe.ProtoReflect.Descriptor instead.
func (*ConfigurationControlDescribe) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{4}
}

type ConfigurationControlDescribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfChannels uint32 `protobuf:"fixed32,1,opt,name=numberOfChannels,proto3" json:"numberOfChannels,omitempty"`
}

func (x *ConfigurationControlDescribeResponse) Reset() {
	*x = ConfigurationControlDescribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationControlDescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationControlDescribeResponse) ProtoMessage() {}

func (x *ConfigurationControlDescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationControlDescribeResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationControlDescribeResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigurationControlDescribeResponse) GetNumberOfChannels() uint32 {
	if x != nil {
		return x.NumberOfChannels
	}
	return 0
}

// ConfigurationControlResponse to pass to Functionblock.ConfigurationControlResponse.functionSpecificConfigurationControlResponse hook
type ConfigurationControlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*ConfigurationControlResponse_Set
	//	*ConfigurationControlResponse_Get
	//	*ConfigurationControlResponse_Describe
	Type isConfigurationControlResponse_Type `protobuf_oneof:"type"`
}

func (x *ConfigurationControlResponse) Reset() {
	*x = ConfigurationControlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurationControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationControlResponse) ProtoMessage() {}

func (x *ConfigurationControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationControlResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationControlResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{6}
}

func (m *ConfigurationControlResponse) GetType() isConfigurationControlResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ConfigurationControlResponse) GetSet() *ConfigurationControlGetResponse {
	if x, ok := x.GetType().(*ConfigurationControlResponse_Set); ok {
		return x.Set
	}
	return nil
}

func (x *ConfigurationControlResponse) GetGet() *ConfigurationControlSetResponse {
	if x, ok := x.GetType().(*ConfigurationControlResponse_Get); ok {
		return x.Get
	}
	return nil
}

func (x *ConfigurationControlResponse) GetDescribe() *ConfigurationControlDescribeResponse {
	if x, ok := x.GetType().(*ConfigurationControlResponse_Describe); ok {
		return x.Describe
	}
	return nil
}

type isConfigurationControlResponse_Type interface {
	isConfigurationControlResponse_Type()
}

type ConfigurationControlResponse_Set struct {
	Set *ConfigurationControlGetResponse `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type ConfigurationControlResponse_Get struct {
	Get *ConfigurationControlSetResponse `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type ConfigurationControlResponse_Describe struct {
	Describe *ConfigurationControlDescribeResponse `protobuf:"bytes,3,opt,name=describe,proto3,oneof"`
}

func (*ConfigurationControlResponse_Set) isConfigurationControlResponse_Type() {}

func (*ConfigurationControlResponse_Get) isConfigurationControlResponse_Type() {}

func (*ConfigurationControlResponse_Describe) isConfigurationControlResponse_Type() {}

// ============= FunctionControl =================
// Sets the value of a single binary channel
type SetSingle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of the binary output channel
	Channel uint32 `protobuf:"fixed32,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// State of the binary output channel
	State bool `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SetSingle) Reset() {
	*x = SetSingle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSingle) ProtoMessage() {}

func (x *SetSingle) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSingle.ProtoReflect.Descriptor instead.
func (*SetSingle) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{7}
}

func (x *SetSingle) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SetSingle) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

// Sets all binary channels
type SetAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// binary coded map of input values. 0 means low, 1 means high, LSB is Output0
	Values uint32 `protobuf:"fixed32,1,opt,name=values,proto3" json:"values,omitempty"`
	// mask to define which channels are affected by the set all command. 0 means not set, 1 means set, LSB is Output0
	Mask uint32 `protobuf:"fixed32,2,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *SetAll) Reset() {
	*x = SetAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAll) ProtoMessage() {}

func (x *SetAll) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAll.ProtoReflect.Descriptor instead.
func (*SetAll) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{8}
}

func (x *SetAll) GetValues() uint32 {
	if x != nil {
		return x.Values
	}
	return 0
}

func (x *SetAll) GetMask() uint32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

// Gets the current value of a single binary channel
type GetSingle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Specifies the binary input channel
	Channel uint32 `protobuf:"fixed32,1,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *GetSingle) Reset() {
	*x = GetSingle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingle) ProtoMessage() {}

func (x *GetSingle) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingle.ProtoReflect.Descriptor instead.
func (*GetSingle) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{9}
}

func (x *GetSingle) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

// Gets the values of all binary channels
type GetAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAll) Reset() {
	*x = GetAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAll) ProtoMessage() {}

func (x *GetAll) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAll.ProtoReflect.Descriptor instead.
func (*GetAll) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{10}
}

// FunctionControlGet to pass to Functionblock.FunctionControl.functionSpecificFunctionControlGet hook
type FunctionControlGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*FunctionControlGet_Single
	//	*FunctionControlGet_All
	Type isFunctionControlGet_Type `protobuf_oneof:"type"`
}

func (x *FunctionControlGet) Reset() {
	*x = FunctionControlGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionControlGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionControlGet) ProtoMessage() {}

func (x *FunctionControlGet) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionControlGet.ProtoReflect.Descriptor instead.
func (*FunctionControlGet) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{11}
}

func (m *FunctionControlGet) GetType() isFunctionControlGet_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FunctionControlGet) GetSingle() *GetSingle {
	if x, ok := x.GetType().(*FunctionControlGet_Single); ok {
		return x.Single
	}
	return nil
}

func (x *FunctionControlGet) GetAll() *GetAll {
	if x, ok := x.GetType().(*FunctionControlGet_All); ok {
		return x.All
	}
	return nil
}

type isFunctionControlGet_Type interface {
	isFunctionControlGet_Type()
}

type FunctionControlGet_Single struct {
	Single *GetSingle `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type FunctionControlGet_All struct {
	All *GetAll `protobuf:"bytes,2,opt,name=all,proto3,oneof"`
}

func (*FunctionControlGet_Single) isFunctionControlGet_Type() {}

func (*FunctionControlGet_All) isFunctionControlGet_Type() {}

// FunctionControlSet to pass to Functionblock.FunctionControl.functionSpecificFunctionControlSet hook
type FunctionControlSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*FunctionControlSet_Single
	//	*FunctionControlSet_All
	Type isFunctionControlSet_Type `protobuf_oneof:"type"`
}

func (x *FunctionControlSet) Reset() {
	*x = FunctionControlSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionControlSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionControlSet) ProtoMessage() {}

func (x *FunctionControlSet) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionControlSet.ProtoReflect.Descriptor instead.
func (*FunctionControlSet) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{12}
}

func (m *FunctionControlSet) GetType() isFunctionControlSet_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FunctionControlSet) GetSingle() *SetSingle {
	if x, ok := x.GetType().(*FunctionControlSet_Single); ok {
		return x.Single
	}
	return nil
}

func (x *FunctionControlSet) GetAll() *SetAll {
	if x, ok := x.GetType().(*FunctionControlSet_All); ok {
		return x.All
	}
	return nil
}

type isFunctionControlSet_Type interface {
	isFunctionControlSet_Type()
}

type FunctionControlSet_Single struct {
	Single *SetSingle `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type FunctionControlSet_All struct {
	All *SetAll `protobuf:"bytes,2,opt,name=all,proto3,oneof"`
}

func (*FunctionControlSet_Single) isFunctionControlSet_Type() {}

func (*FunctionControlSet_All) isFunctionControlSet_Type() {}

type SetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetAllResponse) Reset() {
	*x = SetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAllResponse) ProtoMessage() {}

func (x *SetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAllResponse.ProtoReflect.Descriptor instead.
func (*SetAllResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{13}
}

type SetSingleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetSingleResponse) Reset() {
	*x = SetSingleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSingleResponse) ProtoMessage() {}

func (x *SetSingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSingleResponse.ProtoReflect.Descriptor instead.
func (*SetSingleResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{14}
}

type GetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// binary coded map of input values. 0 means low, 1 means high, LSB is Input0
	Inputs uint32 `protobuf:"fixed32,1,opt,name=inputs,proto3" json:"inputs,omitempty"`
	// binary coded map of errors for each input. 0 means no error, 1 means error, LSB is Input0
	ErrorStatus uint32 `protobuf:"fixed32,2,opt,name=error_status,json=errorStatus,proto3" json:"error_status,omitempty"`
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllResponse) GetInputs() uint32 {
	if x != nil {
		return x.Inputs
	}
	return 0
}

func (x *GetAllResponse) GetErrorStatus() uint32 {
	if x != nil {
		return x.ErrorStatus
	}
	return 0
}

type GetSingleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of the binary input channel
	Channel uint32 `protobuf:"fixed32,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// State for the bianry input channel
	State bool `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *GetSingleResponse) Reset() {
	*x = GetSingleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleResponse) ProtoMessage() {}

func (x *GetSingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleResponse.ProtoReflect.Descriptor instead.
func (*GetSingleResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{16}
}

func (x *GetSingleResponse) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *GetSingleResponse) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

// FunctionControlResponse to pass to Functionblock.FunctionControlResponse.functionSpecificFunctionControlResponse hook
type FunctionControlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*FunctionControlResponse_GetSingle
	//	*FunctionControlResponse_GetAll
	//	*FunctionControlResponse_SetSingle
	//	*FunctionControlResponse_SetAll
	Type isFunctionControlResponse_Type `protobuf_oneof:"type"`
}

func (x *FunctionControlResponse) Reset() {
	*x = FunctionControlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionControlResponse) ProtoMessage() {}

func (x *FunctionControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionControlResponse.ProtoReflect.Descriptor instead.
func (*FunctionControlResponse) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{17}
}

func (m *FunctionControlResponse) GetType() isFunctionControlResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *FunctionControlResponse) GetGetSingle() *GetSingleResponse {
	if x, ok := x.GetType().(*FunctionControlResponse_GetSingle); ok {
		return x.GetSingle
	}
	return nil
}

func (x *FunctionControlResponse) GetGetAll() *GetAllResponse {
	if x, ok := x.GetType().(*FunctionControlResponse_GetAll); ok {
		return x.GetAll
	}
	return nil
}

func (x *FunctionControlResponse) GetSetSingle() *SetSingleResponse {
	if x, ok := x.GetType().(*FunctionControlResponse_SetSingle); ok {
		return x.SetSingle
	}
	return nil
}

func (x *FunctionControlResponse) GetSetAll() *SetAllResponse {
	if x, ok := x.GetType().(*FunctionControlResponse_SetAll); ok {
		return x.SetAll
	}
	return nil
}

type isFunctionControlResponse_Type interface {
	isFunctionControlResponse_Type()
}

type FunctionControlResponse_GetSingle struct {
	GetSingle *GetSingleResponse `protobuf:"bytes,1,opt,name=getSingle,proto3,oneof"`
}

type FunctionControlResponse_GetAll struct {
	GetAll *GetAllResponse `protobuf:"bytes,2,opt,name=getAll,proto3,oneof"`
}

type FunctionControlResponse_SetSingle struct {
	SetSingle *SetSingleResponse `protobuf:"bytes,3,opt,name=setSingle,proto3,oneof"`
}

type FunctionControlResponse_SetAll struct {
	SetAll *SetAllResponse `protobuf:"bytes,4,opt,name=setAll,proto3,oneof"`
}

func (*FunctionControlResponse_GetSingle) isFunctionControlResponse_Type() {}

func (*FunctionControlResponse_GetAll) isFunctionControlResponse_Type() {}

func (*FunctionControlResponse_SetSingle) isFunctionControlResponse_Type() {}

func (*FunctionControlResponse_SetAll) isFunctionControlResponse_Type() {}

// ============= StreamControl ==================
// StreamControlStart to pass to Functionblock.StreamControl.functionSpecificStreamControlStart hook
type StreamControlStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// mask to define which channels are considered in the stream. 0 means don't send channels value, 1 means sent it
	// LSB is Input0
	EnableMask uint32 `protobuf:"fixed32,1,opt,name=enableMask,proto3" json:"enableMask,omitempty"`
}

func (x *StreamControlStart) Reset() {
	*x = StreamControlStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamControlStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControlStart) ProtoMessage() {}

func (x *StreamControlStart) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControlStart.ProtoReflect.Descriptor instead.
func (*StreamControlStart) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{18}
}

func (x *StreamControlStart) GetEnableMask() uint32 {
	if x != nil {
		return x.EnableMask
	}
	return 0
}

type Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timestamp for that specific channels sample. This is the time the sample was taken.
	// This timestamp is in microseconds since the start of the device and does not get synchronized with the clients time.
	Timestamp uint64 `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Specifies the binary channel
	Channel uint32 `protobuf:"fixed32,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Specifies the binary channel value when the input value has changed.
	Value bool `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	// Indicates if the value is valid or invalid.
	// true: value is valid, false: value is invalid
	Valid bool `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Sample) Reset() {
	*x = Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{19}
}

func (x *Sample) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Sample) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Sample) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *Sample) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// StreamData to pass to Functionblock.StreamData.functionSpecificStreamData hook
type StreamData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Samples []*Sample `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binaryIoTypeA_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_binaryIoTypeA_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_binaryIoTypeA_proto_rawDescGZIP(), []int{20}
}

func (x *StreamData) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

var File_binaryIoTypeA_proto protoreflect.FileDescriptor

var file_binaryIoTypeA_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54,
	0x79, 0x70, 0x65, 0x41, 0x22, 0xab, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x74,
	0x12, 0x2c, 0x0a, 0x11, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x72, 0x69, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x4d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x11, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x46, 0x72, 0x69, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x70, 0x12, 0x2c,
	0x0a, 0x11, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x64, 0x6f, 0x67,
	0x4d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x11, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x64, 0x6f, 0x67, 0x4d, 0x61, 0x70, 0x12, 0x34, 0x0a, 0x15,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x64, 0x6f, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x15, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x64, 0x6f, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x22, 0x21, 0x0a, 0x1f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47, 0x65, 0x74,
	0x22, 0x3d, 0x0a, 0x1f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x69, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x08, 0x66, 0x72, 0x69, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22,
	0x1e, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x22,
	0x52, 0x0a, 0x24, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x07, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x22, 0x81, 0x02, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2e, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65,
	0x41, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x42, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f,
	0x54, 0x79, 0x70, 0x65, 0x41, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x03, 0x67, 0x65, 0x74, 0x12, 0x51, 0x0a, 0x08,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x42,
	0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x22, 0x25, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x22, 0x08, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x22, 0x7b, 0x0a, 0x12, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x47, 0x65,
	0x74, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65,
	0x41, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70,
	0x65, 0x41, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c,
	0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x7b, 0x0a, 0x12, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x74, 0x12, 0x32,
	0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e, 0x53,
	0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e,
	0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x42, 0x06, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0b, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x43, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x97,
	0x02, 0x0a, 0x17, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x67, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x67, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x37, 0x0a, 0x06,
	0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x67,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x40, 0x0a, 0x09, 0x73, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x34, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x22, 0x6c,
	0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0a,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x07, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2e, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x52, 0x07, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x62,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_binaryIoTypeA_proto_rawDescOnce sync.Once
	file_binaryIoTypeA_proto_rawDescData = file_binaryIoTypeA_proto_rawDesc
)

func file_binaryIoTypeA_proto_rawDescGZIP() []byte {
	file_binaryIoTypeA_proto_rawDescOnce.Do(func() {
		file_binaryIoTypeA_proto_rawDescData = protoimpl.X.CompressGZIP(file_binaryIoTypeA_proto_rawDescData)
	})
	return file_binaryIoTypeA_proto_rawDescData
}

var file_binaryIoTypeA_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_binaryIoTypeA_proto_goTypes = []interface{}{
	(*ConfigurationControlSet)(nil),              // 0: binaryIoTypeA.ConfigurationControlSet
	(*ConfigurationControlSetResponse)(nil),      // 1: binaryIoTypeA.ConfigurationControlSetResponse
	(*ConfigurationControlGet)(nil),              // 2: binaryIoTypeA.ConfigurationControlGet
	(*ConfigurationControlGetResponse)(nil),      // 3: binaryIoTypeA.ConfigurationControlGetResponse
	(*ConfigurationControlDescribe)(nil),         // 4: binaryIoTypeA.ConfigurationControlDescribe
	(*ConfigurationControlDescribeResponse)(nil), // 5: binaryIoTypeA.ConfigurationControlDescribeResponse
	(*ConfigurationControlResponse)(nil),         // 6: binaryIoTypeA.ConfigurationControlResponse
	(*SetSingle)(nil),                            // 7: binaryIoTypeA.SetSingle
	(*SetAll)(nil),                               // 8: binaryIoTypeA.SetAll
	(*GetSingle)(nil),                            // 9: binaryIoTypeA.GetSingle
	(*GetAll)(nil),                               // 10: binaryIoTypeA.GetAll
	(*FunctionControlGet)(nil),                   // 11: binaryIoTypeA.FunctionControlGet
	(*FunctionControlSet)(nil),                   // 12: binaryIoTypeA.FunctionControlSet
	(*SetAllResponse)(nil),                       // 13: binaryIoTypeA.SetAllResponse
	(*SetSingleResponse)(nil),                    // 14: binaryIoTypeA.SetSingleResponse
	(*GetAllResponse)(nil),                       // 15: binaryIoTypeA.GetAllResponse
	(*GetSingleResponse)(nil),                    // 16: binaryIoTypeA.GetSingleResponse
	(*FunctionControlResponse)(nil),              // 17: binaryIoTypeA.FunctionControlResponse
	(*StreamControlStart)(nil),                   // 18: binaryIoTypeA.StreamControlStart
	(*Sample)(nil),                               // 19: binaryIoTypeA.Sample
	(*StreamData)(nil),                           // 20: binaryIoTypeA.StreamData
}
var file_binaryIoTypeA_proto_depIdxs = []int32{
	3,  // 0: binaryIoTypeA.ConfigurationControlResponse.set:type_name -> binaryIoTypeA.ConfigurationControlGetResponse
	1,  // 1: binaryIoTypeA.ConfigurationControlResponse.get:type_name -> binaryIoTypeA.ConfigurationControlSetResponse
	5,  // 2: binaryIoTypeA.ConfigurationControlResponse.describe:type_name -> binaryIoTypeA.ConfigurationControlDescribeResponse
	9,  // 3: binaryIoTypeA.FunctionControlGet.single:type_name -> binaryIoTypeA.GetSingle
	10, // 4: binaryIoTypeA.FunctionControlGet.all:type_name -> binaryIoTypeA.GetAll
	7,  // 5: binaryIoTypeA.FunctionControlSet.single:type_name -> binaryIoTypeA.SetSingle
	8,  // 6: binaryIoTypeA.FunctionControlSet.all:type_name -> binaryIoTypeA.SetAll
	16, // 7: binaryIoTypeA.FunctionControlResponse.getSingle:type_name -> binaryIoTypeA.GetSingleResponse
	15, // 8: binaryIoTypeA.FunctionControlResponse.getAll:type_name -> binaryIoTypeA.GetAllResponse
	14, // 9: binaryIoTypeA.FunctionControlResponse.setSingle:type_name -> binaryIoTypeA.SetSingleResponse
	13, // 10: binaryIoTypeA.FunctionControlResponse.setAll:type_name -> binaryIoTypeA.SetAllResponse
	19, // 11: binaryIoTypeA.StreamData.samples:type_name -> binaryIoTypeA.Sample
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_binaryIoTypeA_proto_init() }
func file_binaryIoTypeA_proto_init() {
	if File_binaryIoTypeA_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_binaryIoTypeA_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationControlSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationControlSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationControlGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationControlGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationControlDescribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationControlDescribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurationControlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSingle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionControlGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionControlSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSingleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionControlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamControlStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binaryIoTypeA_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_binaryIoTypeA_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ConfigurationControlResponse_Set)(nil),
		(*ConfigurationControlResponse_Get)(nil),
		(*ConfigurationControlResponse_Describe)(nil),
	}
	file_binaryIoTypeA_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*FunctionControlGet_Single)(nil),
		(*FunctionControlGet_All)(nil),
	}
	file_binaryIoTypeA_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*FunctionControlSet_Single)(nil),
		(*FunctionControlSet_All)(nil),
	}
	file_binaryIoTypeA_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*FunctionControlResponse_GetSingle)(nil),
		(*FunctionControlResponse_GetAll)(nil),
		(*FunctionControlResponse_SetSingle)(nil),
		(*FunctionControlResponse_SetAll)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_binaryIoTypeA_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_binaryIoTypeA_proto_goTypes,
		DependencyIndexes: file_binaryIoTypeA_proto_depIdxs,
		MessageInfos:      file_binaryIoTypeA_proto_msgTypes,
	}.Build()
	File_binaryIoTypeA_proto = out.File
	file_binaryIoTypeA_proto_rawDesc = nil
	file_binaryIoTypeA_proto_goTypes = nil
	file_binaryIoTypeA_proto_depIdxs = nil
}
