on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release io4edge-cli Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: "386"
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ldflags: -X github.com/ci4rail/io4edge-client-go/v2/internal/version.Version=${{ github.event.release.tag_name }}
          build_flags: -tags netgo,osusergo,static_build
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.23.2.linux-amd64.tar.gz"
          project_path: "./cmd/cli"
          binary_name: "io4edge-cli"
          extra_files: LICENSE README_CLI.md
