on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release exec_ttynvt Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel
        goos: [linux]
        goarch: ["386", amd64, arm, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ldflags: -X github.com/ci4rail/io4edge-client-go/internal/version.Version=${{ github.event.release.tag_name }}
          build_flags: -tags netgo,osusergo,static_build
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.17.5.linux-amd64.tar.gz"
          project_path: "./cmd/exec_ttynvt"
          binary_name: "exec_ttynvt"
          extra_files: LICENSE README_CLI.md
